name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # This will run every day at 12:00 PM UTC

jobs:
  create-daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Git Config (ramraj.varatharaj@straive.com)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "ramraj.varatharaj@straive.com"
          
      - name: Create and commit daily update
        run: |
          # Create or update a file with current timestamp
          echo "Last updated: $(date)" > last_update.txt
          
          # Add and commit the changes
          git add last_update.txt
          git commit -m "Daily automated update $(date)"
          git push
